// Lista corta de palabras (en minúsculas falta probar con la ñ )
export const validWords = [
 
  'perro', 'gatos', 'silla', 'cielo', 'arbol', 'plaza', 'tigre', 'barco', 'luzco', 'viene',
  'mango', 'fresa', 'piano', 'raton', 'leche', 'panal', 'huevo', 'jugar', 'largo', 'flaco',
  'color', 'verde', 'azul',  'blusa', 'cabra', 'perla', 'arena', 'dulce', 'nieve', 'plato',
  'reloj', 'salud', 'tarde', 'sauce', 'yogur', 'zorro', 'brisa', 'campo', 'dardo', 'fondo',
  'gente', 'hueso', 'joven', 'kilos', 'monte', 'noche', 'orden', 'pista', 'quiso', 'vuelo',
  'yerno', 'zombi', 'abajo', 'abeto', 'abrir', 'abuelo', 'acaba', 'acera', 'acido', 'actor',
  'acusa', 'adios', 'afila', 'agudo', 'airea', 'albor', 'algas', 'altar', 'antes', 'ancho',
  'angel', 'apaga', 'apoyo', 'araña', 'ardor', 'arena', 'armar', 'aroma', 'asado', 'atado',
  'atras', 'avena', 'ayuda', 'baile', 'bajar', 'barro', 'besar', 'besar', 'besos', 'bicho',
  'blusa', 'broma', 'bruma', 'burla', 'calle', 'campo', 'canal', 'canoa', 'canto', 'caoba',
  'carne', 'carta', 'casco', 'casas', 'caspa', 'cebra', 'cerca', 'cesto', 'chapa', 'chela',
  'chico', 'china', 'clave', 'cobre', 'coche', 'comer', 'copas', 'coral', 'corte', 'creer',
  'cruce', 'cuero', 'culpa', 'curar', 'dardo', 'debil', 'dedos', 'denso', 'desde', 'dolar',
  'donar', 'dormir', 'ducha', 'dulce', 'ebrio', 'ecoar', 'edito', 'ejote', 'elote', 'empez',
  'enano', 'encia', 'enfer', 'enojo', 'ensay', 'entra', 'envia', 'epoca', 'error', 'espia',
  'estar', 'etapa', 'exito', 'extra', 'falla', 'feliz', 'feria', 'ficha', 'figar', 'finca',
  'firma', 'firme', 'flaco', 'flama', 'fondo', 'forma', 'fruta', 'fuego', 'fumar', 'gafas',
  'gallo', 'gamba', 'ganar', 'gente', 'golpe', 'gordo', 'grano', 'grito', 'grupo', 'guapo',
  'gusta', 'habit', 'harto', 'hasta', 'helio', 'hielo', 'hijos', 'hojas', 'honor', 'horno',
  'huevo', 'igual', 'ileso', 'impio', 'indice', 'inico', 'invio', 'jaula', 'jefes', 'joven',
  'jugar', 'jugos', 'junto', 'karma', 'kilim', 'lamas', 'largo', 'lento', 'letra', 'libra',
  'lindo', 'llama', 'lleno', 'llora', 'lluvia', 'lucha', 'lugar', 'lujur', 'luzco', 'magma',
  'malas', 'malos', 'manso', 'marco', 'marea', 'marzo', 'mateo', 'medio', 'menor', 'mesas',
  'metal', 'meter', 'metro', 'mirar', 'mitad', 'molde', 'monje', 'morir', 'mover', 'mucho',
  'mudar', 'mujer', 'mundo', 'musgo', 'nacer', 'nadar', 'nadie', 'nariz', 'necio', 'negar',
  'nieve', 'noche', 'norte', 'notas', 'nubes', 'nueva', 'nuevo', 'nunca', 'obras', 'ocaso',
  'oeste', 'ojear', 'ojera', 'oliva', 'omitir', 'opina', 'orden', 'oreja', 'orina', 'osoas',
  'otros', 'ovulo', 'padre', 'pagar', 'pajar', 'pampa', 'pasto', 'patio', 'pauta', 'peces',
  'pelar', 'pelea', 'peloa', 'perla', 'pesar', 'pesca', 'pezon', 'piano', 'pican', 'picar',
  'pieza', 'pilar', 'pinta', 'pisar', 'pista', 'placer', 'plano', 'plata', 'plaza', 'plomo',
  'poder', 'poner', 'porte', 'presa', 'primo', 'prisa', 'priva', 'prueba', 'pulga', 'punto',
  'queso', 'quien', 'quita', 'radio', 'raspa', 'ratos', 'rayos', 'razon', 'recor', 'redes',
  'regla', 'reina', 'rejas', 'relax', 'rente', 'retoz', 'reyes', 'rifle', 'robar', 'rojas',
  'ropa', 'rosas', 'rueda', 'ruido', 'rumor', 'sabor', 'sacar', 'salsa', 'salta', 'salud',
  'sapos', 'sarta', 'satis', 'secar', 'seman', 'senos', 'serio', 'serie', 'servo', 'siembra',
  'silla', 'sirve', 'sitio', 'sobra', 'socios', 'sogas', 'solas', 'solar', 'sonar', 'sondo',
  'sopla', 'sordo', 'suave', 'subir', 'suelo', 'sueño', 'surco', 'tabla', 'tacto', 'tarde',
  'tazas', 'temer', 'tenaz', 'tener', 'tenis', 'terco', 'tierra', 'tirar', 'tocar', 'tomar',
  'tonel', 'tonto', 'torso', 'trago', 'traje', 'tramo', 'trapo', 'trato', 'trece', 'trigo',
  'trono', 'tropa', 'trote', 'tuerc', 'tumba', 'turbo', 'turno', 'tutor', 'ubica', 'ungir',
  'unico', 'untar', 'urgir', 'usado', 'usar', 'usted', 'utero', 'vacas', 'vagon', 'valer',
  'valor', 'vapor', 'varas', 'vaso', 'vasto', 'venir', 'venta', 'verbo', 'verde', 'verdu',
  'verga', 'verso', 'vicio', 'video', 'vigor', 'vimos', 'vinos', 'viola', 'virar', 'vista',
  'vital', 'viven', 'vivir', 'voces', 'volar', 'volco', 'volte', 'vuela', 'vuelo', 'zorro',
  'gatos',  'silla','cielo','arbol',  'plaza',  'tigre',  'barco',  'luzco',  'viene',  'niñez',
  'ñandú',  'mango',  'fresa',  'piano',  'ratón',  'mañana',  'zapato',  'leche',  'panal',
  'huevo',  'jugar',  'largo',  'flaco',  'color',  'verde',  'azul',  'blusa',  'cabra',
  'perla',  'arena',  'dulce',  'frío',  'nieve',  'piedra',  'plato',  'reloj',
  'salud',  'tarde',  'sauce',  'viento',  'yogur',  'zorro',  'brisa',  'campo',
  'dardo',  'eco',  'fondo',  'gente',  'hueso',  'idea',  'joven',  'kilos',
  'luzco',  'monte',  'noche',  'orden',  'pista',  'quiso',  'ratón',  'sauce',
  'tiempo',  'útil',  'vuelo',  'waltz',  'xerox',  'yerno',  'zombi',];
// agregar diccionario con palabras
// Función para elegir palabra al azar y devolverla en mayúsculas
export const getRandomWord = () => {
  return validWords[Math.floor(Math.random() * validWords.length)].toUpperCase();
};
